apiVersion: v1
kind: Pod
metadata:
  name: dumper-pod
  namespace: {{ .Values.namespace | default "not_defined" }}
spec:
  volumes:
  - name: moodle01-storage
    persistentVolumeClaim:
     claimName: {{ .Values.pvc | default "not_defined" }}
  containers:
  - image: mysqlboy/docker-mydumper
    name: dumper
    resources:
      limits:
        cpu: 400m
        memory: 400Mi
      requests:
        cpu: 20m
        memory: 10Mi
    env:
    - name: MDL_DATAROOT
      valueFrom:
        configMapKeyRef:
          name: moodle01-config
          key: dataroot
    - name: MDL_DBHOST
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_host
    - name: MDL_DBNAME
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_name
    - name: MDL_DBUSER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_username
    - name: MDL_DBPASS
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_password
    volumeMounts:
    - mountPath: {{ .Values.dataroot | default "/mnt/NFS" }}
      name: moodle01-storage

    args:
    - /bin/sh
    - -c
    - mydumper --user=${MDL_DBUSER} --password=${MDL_DBPASS} --host=${MDL_DBHOST} \ 
      --outputdir=${MDL_DATAROOT}/backups/$( date +%Y-%m-%d_%T ) --rows=500000 \
      --compress --build-empty-files --threads=4 --compress-protocol -k --lock-all-tables \
      -v 3 
      --database {{ .Values.bd | default "cecl" }}
  restartPolicy: Never