apiVersion: v1
kind: Pod
metadata:
  name: loader-pod
  namespace: {{ .Values.namespace | default "not_defined" }}
spec:
  volumes:
  - name: moodle01-storage
    persistentVolumeClaim:
     claimName: {{ .Values.pvc | default "not_defined" }}
  containers:
  - image: mysqlboy/docker-mydumper
    name: loader-{{ .Values.bckdate | default "not_defined }}
    resources:
      limits:
        cpu: 400m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 100Mi
    env:
    - name: MDL_DATAROOT
      valueFrom:
        configMapKeyRef:
          name: moodle01-config
          key: dataroot
    - name: MDL_DBHOST
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_host
    - name: MDL_DBNAME
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_name
    - name: MDL_DBUSER
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_username
    - name: MDL_DBPASS
      valueFrom:
        secretKeyRef:
          name: {{ .Values.secrets | default "secrets-moodle01-prod" }}
          key: db_password
    volumeMounts:
    - mountPath: {{ .Values.dataroot | default "/mnt/NFS" }}
      name: moodle01-storage
    args:
    - /bin/sh
    - -c
    - myloader --user=${MDL_DBUSER} --password=${MDL_DBPASS} --host=${MDL_DBHOST} \
      --directory="${MDL_DATAROOT}/backups/{{ .Values.bckdate | default "not_defined" }}" 
      --overwrite-tables --threads=10 --compress-protocol
  restartPolicy: Never