apiVersion: v1
kind: Pod
metadata:
  name:   siad-jenkins-jenkins
  namespace: siad-jenkins-dev-01
  labels:
    app: siad-jenkins-jenkins-01

spec:
  containers:
    #- image: wsimmonds/jenkins-kubernetes:2.8
    - image: nmolleruq/jenkkube:1.0
    #- image: csanchez/jenkins-kubernetes:0.11
      name: siad-jenkins-jenkins-01
      #command: ["chown"]
      #args: ["1000:1000", "/var/run/docker.sock"]
      ports:
        - containerPort: 8080
        - containerPort: 50000
      volumeMounts:
        - mountPath: "/var/jenkins_home"
          name: siad-jenkins-dev-01-storage
        #- mountPath: "/var/run/docker.sock"
        #  name: siad-jenkins-dev-01-sock
  #securityContext: 
            #fsGroup: 1000         
  volumes:
    - name: siad-jenkins-dev-01-storage
      persistentVolumeClaim:
       claimName: pvc-siad-jenkins-dev-01
    #- name: siad-jenkins-dev-01-sock
    #  persistentVolumeClaim:
    #   claimName: pvc-siad-jenkins-docker-socket