apiVersion: v1
kind: Pod
metadata:
  name:   siad-jenkins-jenkins
  namespace: siad-jenkins-dev-01
  labels:
    app: siad-jenkins-jenkins-01

spec:
  containers:
    - image: jenkins
      name: siad-jenkins-jenkins-01
      ports:
        - containerPort: 8080
        - containerPort: 50000
      #volumeMounts:
      #  - mountPath: "/var/jenkins_home"
      #    name: siad-jenkins-dev-01-storage
      # command: []
      # args: ["-u 1000"]
  #volumes:
    #- name: siad-jenkins-dev-01-storage
    #  persistentVolumeClaim:
    #   claimName: pvc-siad-jenkins-dev-01