kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-siad-jenkins-dev-01
  namespace: siad-jenkins-dev-01
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi