apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: moodle01-deployment
  namespace: siad-moodle-dev-01
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: moodle01-dev
    spec:
      volumes:
      - name: moodle01-storage
        persistentVolumeClaim:
         claimName: pvc-siad-moodle-dev-01-vol01
      containers:
      - name: moodle01-dev
        image: eboraas/apache-php
        volumeMounts:
          - mountPath: "/var/www"
            name: moodle01-storage
        resources:
              limits:
                cpu: 70m
                memory: 90Mi
              requests:
                cpu: 50m
                memory: 70Mi
        ports:
        - containerPort: 80
        - containerPort: 443